language: php

php:
  - 5.3
  - 5.4

before_install:
  - cd ../
  - git clone git://github.com/UnionOfRAD/framework.git
  - mv li3_waffle/ framework/app/libraries/li3_waffle
  - cd framework
  - git submodule update --init --recursive
  - cd libraries/lithium && git pull --rebase origin master && cd ../../app/
  - sed '$d' config/bootstrap/libraries.php > config/bootstrap/testlibraries.php
  - echo "Libraries::add('li3_waffle');" >> config/bootstrap/testlibraries.php
  - mv config/bootstrap/testlibraries.php config/bootstrap/libraries.php
  - cd ./libraries/li3_waffle

script: ../../../libraries/lithium/console/li3 test tests